### PR TITLE
cdrtools: add recipes for 3.01 and 3.02a06

### PR DESCRIPTION
**Pull request by fbrosson**

### CODE REVIEW

**Comment by lucasvr** [comment]
Greetings, and thanks for the patch.

We usually do not include instructions in the recipe for fetching external contents through wget. If you want to include a patch file, it is just enough to place it in the same directory as the Recipe file. It will be automatically applied by Compile as long as it has a ".patch" extension. 

Could you please make that change and remove the pre_patch() function (as it won't be necessary anymore)?

Thanks!
Lucas

**Comment by fbrosson** [comment]
Hi, and thanks for the previous merge!
Of course, I can do the changes you describe.
The reason why I used an external patch was because I thought it was better to do so, like it was the case for [Gaim/0.74](https://github.com/gobolinux/Recipes/blob/master/trunk/Gaim/0.74/Recipe) and  [Gaim/0.74-r1](https://github.com/gobolinux/Recipes/blob/master/revisions/Gaim/0.74-r1/Recipe) before the body of the pre_build function got commented out. What do you think? No regrets for an external patch with an md5 check? Just confirm you prefer the to have a copy of the patch in the repo and I'll do the changes.
BTW, should I replace the "Glibc 2.14" by "Glibc 2.18" (or anythiing else) in the Resources/BuildInformation of trunk/CDRTools/3.01 and revisions/CDRTools/3.01-r1 ?
Thanks!

**Comment by fbrosson** [comment]
BTW, if sha256sum is available then I can replace the md5 check by a sha256 check for the patch (which would be safer because md5 has become quite weak), unless you prefer to have the patch added to the repo (in which case I'll fix my commit as you described).
Last but not least: I plan to also add a recipe for 3.02a06 (which does not need any patch). Shall I merge it using this same PR? If you prefer I can also drop 3.01 and just add 3.02a06 to this PR. What do you think? 3.02a06 is much better than 3.01 and has no know bugs. Cheers

**Comment by mwh** [comment]
You should include the patch in the recipe. You don't need to edit BuildInformation.

It's generally better to use ContributeRecipe (or mailing in the recipe tarball) rather than pull requests, because then the tools deal with all the administrative minutiae for you. They are tricky to get right otherwise (the changes from the previous merge won't ever actually be picked up, since it just changes historical information).

**Comment by fbrosson** [comment]
OK, thanks. I've fixed 3.01 and also added 3.02a06. I cannot test the recipes because I haven't installed GoboLinux yet, and, consequently, I don't have ContributeRecipe, sorry... But I guess that's ok to use PRs in GitHub until I find some time to install GoboLinux. I've added a couple of optional depends for 3.02a06 because cdda2wav has support for playing tracks to PulseAudio (if it was detected at buildtime and it also falls back to ALSA if pulse is not available at runtime), but both of these are not required. Do not hesitate to ask for m fixes or changes ;-) Thanks!
BTW, if you are OK with also having 3.02a06 in this same PR, then I can change the title of the PR if you wish.

**Comment by lucasvr** [comment]
I'm fine with merging the two versions in this same PR. And thanks again!

**Comment by fbrosson** [comment]
Cool!

**Pull request merged**
