### PR TITLE
XFCE 4.14

### PR DESCRIPTION
**Pull request by ermo**
DO NOT MERGE YET!

Using this as a test-bed for my `ContributeRecipe` improvements.

### CODE REVIEW

**Comment by waldyrious** [comment]
Hey @ermo, @Nuc1eoN — can you comment on how this relates to #61?

**Comment by ermo** [comment]
> Hey @ermo, @Nuc1eoN — can you comment on how this relates to #61?

It's supposed to be an improvement. YMMV.

**Comment by Nuc1eoN** [comment]
Hey @ermo what is the state of this, now that you've pushed #133 ?

**Comment by ermo** [comment]
> Hey @ermo what is the state of this, now that you've pushed #133 ?

No idea as I haven't started my gobo box in a long time. Your guess is as good as mine IOW.

**Pull request closed without merging**
