### PR TITLE
CIFS-Utils 7.0

### PR DESCRIPTION
**Pull request by sage-etcher**
setup a base install of Gobo017 in a qemu vm.
updated `Resources/Dependencies` files for all base software.
did some basic setup: internet, ssh keys, basic aliases, ect.
applied known issues and fixes
entered a snapshot
`NewVersion`ed to 7.0, replacing the broken link with new
Compiled with the `--pure` flag
checked shared libraries for the program and updated `Dependencies` file accordingly.

### CODE REVIEW

**Comment by Nuc1eoN** [comment]
What happened to your previous gobo install?

I'm gonna have to release a 017.01 ISO soon with the "Known issues and fixes" applied... Then 017.02 will focus on tools bug fixes, I guess. In 018 I plan to ship a new wayland based desktop environment aswell, redo the bootloader/kernel/initramfs generation, and an updated recipe set based on `--pure`.

Will test the recipe later. Thank you for compiling it with `--pure` aswell.

**Comment by sage-etcher** [comment]
My previous install is still alright. I'd created the new one to make sure that I could get dependencies (and versions) more accurate, i.e. using snapshots and pure with a (mostly) standard install.

Unrelated, but at some point my main VM's desktop manager stopped working, I normally run it in text mode, so I couldn't say when it broke or what caused it. I don't think I've compiled any desktop related programs on it, except gvim, so I thought it quite bizarre. I don't use it, so it doesn't affect my use, but seemed strange.

**Comment by Nuc1eoN** [comment]
>My previous install is still alright. I'd created the new one to make sure that I could get dependencies (and versions) more accurate, i.e. using snapshots and pure with a (mostly) standard install.

Oh good idea. Thank you for being so diligent. That is exactly the thought behind making Recipes more reproducible. Basically we need a "standard" environment that we test our recipes against. But the GoboLinux ISO is pretty big. So basically we need to trim that down, similar to minimalist alpine or debian docker images.

>Unrelated, but at some point my main VM's desktop manager stopped working

Hmm does GoboLinux have a desktop manager? I am just using startx.


>I'll be looking forward to the release of them new versions =DD

I will do the GoboLinux 017.01 release (basically releasing a new ISO with the fixes that are already available). However after that I could definitely use some assistance. Currently no one else is actively working on goboLinux sadly. So depending on, maybe your contributions too, the new releases will be shaped.

**Comment by Nuc1eoN** [comment]
Package builds fine. Merging.

**Comment by sage-etcher** [comment]
> Unrelated, but at some point my main VM's desktop manager stopped working

I was referring to `startx`/`xinit` here, poor wording on my part, apologies.

**Comment by Nuc1eoN** [comment]
>I was referring to startx/xinit here, poor wording on my part, apologies.

I see. Do you mean Xorg is crashing? Did you fiddle with your kernel?

**Comment by sage-etcher** [comment]
Nope, I didn't touch the kernel, at least not to my knowledge? I didn't touched `lua` or `awesome` neither

This is output from `startx`:
```
$ startx
xauth:  file /Users/dev/.serverauth.1779 does not exist
<CTRL+C><CTRL+C><CTRL+C><CTRL+C>

X.Org X Server 1.20.7
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.9.16-Gobo x86_64 GoboLinux
Current Operating System: Linux GoboEnv 5.6.10-Gobo #1 SMP PREEMPT Tue May 5 12:22:44 -03 2020 x86_64
Kernel command line: BOOT_IMAGE=/System/Kernel/Boot/kernel root=PARTUUID=c2de8c61-01 ro vt.default_utf8=1 brd.rd_nr=0 hid_apple.iso_layout=0 hid_apple.fnmode=2 video=LVDS-1:e video=HDMI-1:e video=VGA=1:e rootwait net.ifnames=0 video=vesafb:off
Build Date: 19 February 2020  08:45:13PM
 
Current version of pixman: 0.38.4
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/Data/Variable/log/Xorg.0.log", Time: Thu Apr 18 09:17:54 2024
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported high keycode 372 for name <I372> ignored
>                   X11 cannot support keycodes above 255.
>                   This warning only shows for the first high keycode.
Errors from xkbcomp are not fatal to the X server
(EE) Failed to open authorization file "/Users/dev/.serverauth.1779": No such file or directory
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported high keycode 372 for name <I372> ignored
>                   X11 cannot support keycodes above 255.
>                   This warning only shows for the first high keycode.
Errors from xkbcomp are not fatal to the X server
awesome: symbol lookup error: awesome: undefined symbol: lua_newuserdata
xinit: connection to X server lost

waiting for X server to shut down (II) Server terminated successfully (0). Closing log file.

xauth:  timeout in locking authority file /Users/dev/.Xauthority
```

the `.serverauth.1779` file doesn't exists, these are the main X related files there. If you `touch .serverauth.1779`, then the first error line doesn't show, and the `CTRL-C`s are not needed, but everything else persists.
```
$ ls -la $HOME
[...]
drwxr--r-- 20 dev  users  4096 Apr 18 09:25 ./
-rw-------  1 dev  users     0 Apr 11 09:23 .Xauthority
-rw-------  2 dev  users     0 Apr 11 09:23 .Xauthority-c
-rw-------  2 dev  users     0 Apr 11 09:23 .Xauthority-l
-rw-r--r--  1 dev  users  2626 Mar 21 04:12 .Xresources
[...]
```

**Comment by Nuc1eoN** [comment]
>edit:
nvm I'm blind, apologies, at some point Lua WAS updated to 5.4.3 and as per
https://github.com/gobolinux/Recipes/issues/128#issue-831017362, awesome broke. I don't remember touching it, but it looks like it got updated March 21st, when installing NeoVim (just a few hours after making this VM). Surprised it took that long to notice.

@sage-etcher oh just noticed the edit! Well thank you for that heads up that lua still needs fixing!

**Pull request merged**
