### PR TITLE
LibAtomic_Ops 7.6.6

### PR DESCRIPTION
**Pull request by ivmai**

### CODE REVIEW

**Comment by lucasvr** [comment]
Thank you, Ivan

**Comment by waldyrious** [comment]
@lucasvr similar to #33 — shouldn't these files have been added to the root directory, rather than [`trunk/`](https://github.com/gobolinux/Recipes/tree/master@%7B2020-07-23%7D/trunk)?

**Comment by lucasvr** [comment]
@waldyrious: ooops, good catch! I'll fix this one and the other you pointed me to. Thanks for the review!

**Comment by lucasvr** [comment]
Done.

**Comment by waldyrious** [comment]
For future reference, the move was done in df5db54a2 and 75f273f34.

**Pull request merged**
